(defun n-hint (n input)
  (cond ((> n input)
	 (format t "nは~Aよりおおきい~%" input)
	 nil)
	((< n input)
	 (format t "nは~Aよりちいさい~%" input)
	 nil)
	((= n input)
	 (format t "~A = ~A~%" n input)
	 )
	)
  (cond ((= (mod n 10) (mod input 10))
	 (format t "nと~Aの一の位はひとしい~%" input)))
  (cond ((= (- n (mod n 10)) (- input (mod input 10)))
	 (format t "nと~Aの十の位はひとしい~%" input)))
  )

(defun find-num-game (n)
  (format t "入力しろ:")
  (let* ((input (parse-integer (read-line))))
    (cond ((= n input)
	   t)
	  (t
	   (n-hint n input)
	   (find-num-game n))
	  )
    )
  )

(defun random-range (min max)
  (+ min (random (+ 1 (- max min)))))

(defun random-set-find-num-game ()
  (find-num-game (random-range 10 99)))
